AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Timestamp:
    Type: String
  LayerBundle:
    Type: String
Resources:
  AwsXraySDK:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: predict-lambda-layers
        S3Key: !Sub
          - ${LayerBundle}_${Timestamp}.zip
          - Timestamp: !Ref Timestamp
      Description: AWS X-Ray SDK for Python.
      LayerName: AwsXraySDK
Outputs:
  AwsXraySDK:
    Value: !Ref AwsXraySDK
    Export:
      Name: AwsXraySDK
