AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LCLatestVersion:
    Type: String
  MonitoringLatestVersion:
    Type: String
  RequestsLatestVersion:
    Type: String

Resources:
  LoggingConfig:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: predict-lambda-layers
        S3Key: lc_layer_pack.zip
        S3ObjectVersion: !Ref LCLatestVersion
      Description: Dependencies required for structured logging and configurations. Structured logging settings.
      LayerName: LoggingConfig

  Monitoring:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: predict-lambda-layers
        S3Key: monitoring_layer_pack.zip
        S3ObjectVersion: !Ref MonitoringLatestVersion
      Description: 'Monitoring Layer: Sentry + AWS X-Ray SDK for Python.'
      LayerName: Monitoring

  Requests:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
          S3Bucket: predict-lambda-layers
          S3Key: requests_layer_pack.zip
          S3ObjectVersion: !Ref RequestsLatestVersion
      Description: Dependencies required for web requests.
      LayerName: Requests
