AWSTemplateFormatVersion: 2010-09-09
Resources:
  LoggingConfig:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
          S3Bucket: predict-lambda-layers
          S3Key: lc_layer_pack.zip 
      Description: Dependencies required for structured logging and configurations. Structured logging settings.
      LayerName: LoggingConfig
Outputs:
  LoggingConfig:
    Value: !Ref LoggingConfig
    Export:
      Name: LoggingConfig

