AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Timestamp:
    Type: String
  LayerBundle:
    Type: String
Resources:
  Monitoring:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: predict-lambda-layers
        S3Key: !Sub
          - ${LayerBundle}_${Timestamp}.zip
          - Timestamp: !Ref Timestamp
      Description: 'Monitoring Layer: Sentry + AWS X-Ray SDK for Python.'
      LayerName: Monitoring
Outputs:
  Monitoring:
    Value: !Ref Monitoring
    Export:
      Name: Monitoring
